name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, pdo, pdo_sqlite, pdo_mysql

      - name: Use composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml --colors=always

  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.4]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v4
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo

      - name: Use composer cache
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --no-interaction

      - name: Run PHP CS Fixer (dry-run)
        run: composer fix:ci